### PR TITLE
NVSHAS-9413: UI-Ext: Compliance page

### PR DESCRIPTION
**Pull request by rushk014**

### CODE REVIEW

**Comment by xingzhang-suse** [comment]
When clicking pie chart button on a selected compliance, the chart is not shown.
Screen Shot 2024-09-16 at 9 51 54 PM

**Comment by xingzhang-suse** [comment]
There is not CSV report for compliance list.

**Comment by xingzhang-suse** [comment]
As the image does not have external link, we don't use pointer as cursor. Please change it into default which is the same as NeuVector.
Screen Shot 2024-09-16 at 10 02 00 PM

**Comment by xingzhang-suse** [comment]
In advanced filter, when I add filter for node, container, service, image, they can be added at the same configuration in NeuVector, but it cannot be added in UI extension.
When I try to choose node on the criteria list after service filter was set, the option cannot be selected in the dropdown.
Screen Shot 2024-09-16 at 10 06 19 PM
Screen Shot 2024-09-16 at 10 06 29 PM

**Review by xingzhang-suse — COMMENTED** [review]
Added issues in the conversation. Please fix the issues. Thank you.

**Comment by rushk014** [comment]
@xingzhang-suse All issues should now be fixed, thanks for the input

**Review by xingzhang-suse — APPROVED** [review]

**Pull request merged**
